# version: "3"
# services:
#   db:
#     image: postgres:15
#     ports:
#       - 5432:5432
#     environment:
#       POSTGRES_DB: db
#       POSTGRES_USER: postgres
#       POSTGRES_HOST_AUTH_METHOD: trust
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#   backend:
#     depends_on:
#       - db
#     build: .
#     ports:
#       - 3000:3000
#     environment:
#       DB_NAME: db
#       DB_USER: postgres
#       DB_PWD: password
#       DB_HOST: db
#       DB_PORT: 5432
#   client:
#     depends_on:
#       - backend
#     build: ./client
#     ports:
#       - 5173:5173
# volumes:
#   pgdata:

version: '3'
services:
  db:
    image: postgres:15
    container_name: watchlist_db
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    command: 
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  backend:
    build: .
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    depends_on:
      - db
    ports:
      - "3000:3000"
  front:
    depends_on:
      - backend
    build: ./client
    ports:
      - 5173:5173
# volumes:
#   pgdata: {}